import createBaseObject from './base-object'

export const Caja1 = createBaseObject('caja-1')
export const Catto = createBaseObject('catto')
export const Disco1 = createBaseObject('disco-1')
export const Disco2 = createBaseObject('disco-2')
export const Disco3 = createBaseObject('disco-3')
export const Esp32 = createBaseObject('esp-32')
export const Gorro = createBaseObject('gorro')
export const Lapiz = createBaseObject('lapiz')
export const Libro1 = createBaseObject('libro-1')
export const Libro2 = createBaseObject('libro-2')
export const Libro3 = createBaseObject('libro-3')
export const MasterChief = createBaseObject('master-chief')
export const Meme = createBaseObject('meme')
export const Monedo = createBaseObject('monedo')
export const Pendrive = createBaseObject('pendrive')
export const Pin1 = createBaseObject('pin-1')
export const Pin2 = createBaseObject('pin-2')
export const Protoboard = createBaseObject('protoboard')
export const RaspberryPi3b = createBaseObject('raspberry-pi')
export const Sticker1 = createBaseObject('sticker-1')
export const Sticker2 = createBaseObject('sticker-2')
export const Sticker3 = createBaseObject('sticker-3')
export const Yubikey = createBaseObject('yubikey')
