name: CI

on:
  # Runs when a push is done to dev
  push:
    branches: [master]
  # Runs when a PR is created to dev
  pull_request:
    branches: [master]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Use node 22
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: Install packages
        run: npm ci

      - name: Check linter
        run: npm run lint --workspaces --if-present

      - name: Build
        run: npm run build --workspaces --if-present
