name: Node.js Package

on:
  # Publish npm package when this tag is created
  push:
    tags: [ '@melchor629/hny-scripts@*.*.*' ]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: https://npm.pkg.github.com
      - run: yarn
      - run: npx lerna publish from-package -y
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
